export const BASE_URL = 'https://soronto3603.github.io/tft/constances/';

export const DATA_URLS = {
  LightAlchemist: 'Light-Alchemist-synergies.json',
  LightMystic: 'Light-Mystic-synergies.json',
  LightAssassin: 'Light-Assassin-synergies.json',
  LightOcean: 'Light-Ocean-synergies.json',
  LightAvatar: 'Light-Avatar-synergies.json',
  LightPoison: 'Light-Poison-synergies.json',
  LightBerserker: 'Light-Berserker-synergies.json',
  LightPredator: 'Light-Predator-synergies.json',
  LightBlademaster: 'Light-Blademaster-synergies.json ',
  LightRanger: 'Light-Ranger-synergies.json',
  LightCrystal: 'Light-Crystal-synergies.json',
  LightShadow: 'Light-Shadow-synergies.json',
  LightDesert: 'Light-Desert-synergies.json',
  LightSoulbound: 'Light-Soulbound-synergies.json',
  LightDruid: 'Light-Druid-synergies.json',
  LightSteel: 'Light-Steel-synergies.json',
  LightElectric: 'Light-Electric-synergies.json',
  LightSummoner: 'Light-Summoner-synergies.json',
  LightGlacial: 'Light-Glacial-synergies.json',
  LightWarden: 'Light-Warden-synergies.json',
  LightInferno: 'Light-Inferno-synergies.json',
  LightWind: 'Light-Wind-synergies.json',
  LightLight: 'Light-Light-synergies.json',
  LightWoodland: 'Light-Woodland-synergies.json',
  LightMage: 'Light-Mage-synergies.json',
  LightMountain: 'Light-Mountain-synergies.json',
  ShadowAssassin: 'Shadow-Assassin-synergies.json',
  ShadowAvatar: 'Shadow-Avatar-synergies.json',
  ShadowBerserker: 'Shadow-Berserker-synergies.json',
  ShadowBlademaster: 'Shadow-Blademaster-synergies.json',
  ShadowCrystal: 'Shadow-Crystal-synergies.json',
  ShadowDesert: 'Shadow-Desert-synergies.json',
  ShadowDruid: 'Shadow-Druid-synergies.json',
  ShadowElectric: 'Shadow-Electric-synergies.json',
  ShadowGlacial: 'Shadow-Glacial-synergies.json',
  ShadowInferno: 'Shadow-Inferno-synergies.json',
  ShadowLight: 'Shadow-Light-synergies.json',
  ShadowMage: 'Shadow-Mage-synergies.json',
  ShadowMountain: 'Shadow-Mountain-synergies.json',
  ShadowMystic: 'Shadow-Mystic-synergies.json',
  ShadowOcean: 'Shadow-Ocean-synergies.json',
  ShadowPoison: 'Shadow-Poison-synergies.json',
  ShadowPredator: 'Shadow-Predator-synergies.json',
  ShadowRanger: 'Shadow-Ranger-synergies.json',
  Shadowahadow: 'Shadow-Shadow-synergies.json',
  ShadowSoulbound: 'Shadow-Soulbound-synergies.json',
  ShadowSteel: 'Shadow-Steel-synergies.json',
  ShadowSummoner: 'Shadow-Summoner-synergies.json',
  ShadowWarden: 'Shadow-Warden-synergies.json',
  ShadowWind: 'Shadow-Wind-synergies.json',
  ShadowWoodland: 'Shadow-Woodland-synergies.json',
  ShadowAlchemist: 'Shadow-Alchemist-synergies.json',
}

export const SYNERGIES = [
  'Alchemist',
  'Mystic',
  'Assassin',
  'Ocean',
  'Avatar',
  'Poison',
  'Berserker',
  'Predator',
  'Blademaster',
  'Ranger',
  'Crystal',
  'Shadow',
  'Desert',
  'Soulbound',
  'Druid',
  'Steel',
  'Electric',
  'Summoner',
  'Glacial',
  'Warden',
  'Inferno',
  'Wind',
  'Light',
  'Woodland',
  'Mage',
  'Mountain',
];

export const store = {
  Alchemist: null,
  Alchemist: null,
  Mystic: null,
  Assassin: null,
  Ocean: null,
  Avatar: null,
  Poison: null,
  Berserker: null,
  Predator: null,
  Blademaster: null,
  Ranger: null,
  Crystal: null,
  Shadow: null,
  Desert: null,
  Soulbound: null,
  Druid: null,
  Steel: null,
  Electric: null,
  Summoner: null,
  Glacial: null,
  Warden: null,
  Inferno: null,
  Wind: null,
  Light: null,
  Woodland: null,
  Mage: null,
  Mountain: null,
}

export async function loadData(synergy) {
  if (store[synergy] === null) {
    const combs = await (await fetch(BASE_URL + DATA_URLS[synergy])).json()
    combs.sort((a, b) => Object.values(b.synergies).reduce((p, c) => p + c) - Object.values(a.synergies).reduce((p, c) => p + c))
    store[synergy] = combs
  }
  return store[synergy]
}