export const BASE_URL = 'https://soronto3603.github.io/tft/constances/';

export const DATA_URLS = {
  Alchemist: 'Light-Alchemist-synergies.json',
  Mystic: 'Light-Mystic-synergies.json',
  Assassin: 'Light-Assassin-synergies.json',
  Ocean: 'Light-Ocean-synergies.json',
  Avatar: 'Light-Avatar-synergies.json',
  Poison: 'Light-Poison-synergies.json',
  Berserker: 'Light-Berserker-synergies.json',
  Predator: 'Light-Predator-synergies.json',
  Blademaster: 'Light-Blademaster-synergies.json ',
  Ranger: 'Light-Ranger-synergies.json',
  Crystal: 'Light-Crystal-synergies.json',
  Shadow: 'Light-Shadow-synergies.json',
  Desert: 'Light-Desert-synergies.json',
  Soulbound: 'Light-Soulbound-synergies.json',
  Druid: 'Light-Druid-synergies.json',
  Steel: 'Light-Steel-synergies.json',
  Electric: 'Light-Electric-synergies.json',
  Summoner: 'Light-Summoner-synergies.json',
  Glacial: 'Light-Glacial-synergies.json',
  Warden: 'Light-Warden-synergies.json',
  Inferno: 'Light-Inferno-synergies.json',
  Wind: 'Light-Wind-synergies.json',
  Light: 'Light-Light-synergies.json',
  Woodland: 'Light-Woodland-synergies.json',
  Mage: 'Light-Mage-synergies.json',
  Mountain: 'Light-Mountain-synergies.json',
};
export const SYNERGIES = [
  'Alchemist',
  'Mystic',
  'Assassin',
  'Ocean',
  'Avatar',
  'Poison',
  'Berserker',
  'Predator',
  'Blademaster',
  'Ranger',
  'Crystal',
  'Shadow',
  'Desert',
  'Soulbound',
  'Druid',
  'Steel',
  'Electric',
  'Summoner',
  'Glacial',
  'Warden',
  'Inferno',
  'Wind',
  'Light',
  'Woodland',
  'Mage',
  'Mountain',
];

export const store = {
  Alchemist: null,
  Alchemist: null,
  Mystic: null,
  Assassin: null,
  Ocean: null,
  Avatar: null,
  Poison: null,
  Berserker: null,
  Predator: null,
  Blademaster: null,
  Ranger: null,
  Crystal: null,
  Shadow: null,
  Desert: null,
  Soulbound: null,
  Druid: null,
  Steel: null,
  Electric: null,
  Summoner: null,
  Glacial: null,
  Warden: null,
  Inferno: null,
  Wind: null,
  Light: null,
  Woodland: null,
  Mage: null,
  Mountain: null,
}

export async function loadData(synergy) {
  if (store[synergy] === null) {
    const combs = await (await fetch(BASE_URL + DATA_URLS[synergy])).json()
    combs.sort((a, b) => Object.values(b.synergies).reduce((p, c) => p + c) - Object.values(a.synergies).reduce((p, c) => p + c))
    store[synergy] = combs
  }
  return store[synergy]
}