export const BASE_URL = 'https://soronto3603.github.io/tft/constances/';

export const DATA_URLS = {
  LightAlchemist: 'Light-Alchemist-synergies.json',
  LightMystic: 'Light-Mystic-synergies.json',
  LightAssassin: 'Light-Assassin-synergies.json',
  LightOcean: 'Light-Ocean-synergies.json',
  LightAvatar: 'Light-Avatar-synergies.json',
  LightPoison: 'Light-Poison-synergies.json',
  LightBerserker: 'Light-Berserker-synergies.json',
  LightPredator: 'Light-Predator-synergies.json',
  LightBlademaster: 'Light-Blademaster-synergies.json ',
  LightRanger: 'Light-Ranger-synergies.json',
  LightCrystal: 'Light-Crystal-synergies.json',
  LightShadow: 'Light-Shadow-synergies.json',
  LightDesert: 'Light-Desert-synergies.json',
  LightSoulbound: 'Light-Soulbound-synergies.json',
  LightDruid: 'Light-Druid-synergies.json',
  LightSteel: 'Light-Steel-synergies.json',
  LightElectric: 'Light-Electric-synergies.json',
  LightSummoner: 'Light-Summoner-synergies.json',
  LightGlacial: 'Light-Glacial-synergies.json',
  LightWarden: 'Light-Warden-synergies.json',
  LightInferno: 'Light-Inferno-synergies.json',
  LightWind: 'Light-Wind-synergies.json',
  LightLight: 'Light-Light-synergies.json',
  LightWoodland: 'Light-Woodland-synergies.json',
  LightMage: 'Light-Mage-synergies.json',
  LightMountain: 'Light-Mountain-synergies.json',
  ShadowAssassin: 'Shadow-Assassin-synergies.json',
  ShadowAvatar: 'Shadow-Avatar-synergies.json',
  ShadowBerserker: 'Shadow-Berserker-synergies.json',
  ShadowBlademaster: 'Shadow-Blademaster-synergies.json',
  ShadowCrystal: 'Shadow-Crystal-synergies.json',
  ShadowDesert: 'Shadow-Desert-synergies.json',
  ShadowDruid: 'Shadow-Druid-synergies.json',
  ShadowElectric: 'Shadow-Electric-synergies.json',
  ShadowGlacial: 'Shadow-Glacial-synergies.json',
  ShadowInferno: 'Shadow-Inferno-synergies.json',
  ShadowLight: 'Shadow-Light-synergies.json',
  ShadowMage: 'Shadow-Mage-synergies.json',
  ShadowMountain: 'Shadow-Mountain-synergies.json',
  ShadowMystic: 'Shadow-Mystic-synergies.json',
  ShadowOcean: 'Shadow-Ocean-synergies.json',
  ShadowPoison: 'Shadow-Poison-synergies.json',
  ShadowPredator: 'Shadow-Predator-synergies.json',
  ShadowRanger: 'Shadow-Ranger-synergies.json',
  Shadowahadow: 'Shadow-Shadow-synergies.json',
  ShadowSoulbound: 'Shadow-Soulbound-synergies.json',
  ShadowSteel: 'Shadow-Steel-synergies.json',
  ShadowSummoner: 'Shadow-Summoner-synergies.json',
  ShadowWarden: 'Shadow-Warden-synergies.json',
  ShadowWind: 'Shadow-Wind-synergies.json',
  ShadowWoodland: 'Shadow-Woodland-synergies.json',
  ShadowAlchemist: 'Shadow-Alchemist-synergies.json',
  BaseAlchemist: 'base-Alchemist-synergies.json',
  BaseMystic: 'base-Mystic-synergies.json',
  BaseAssassin: 'base-Assassin-synergies.json',
  BaseOcean: 'base-Ocean-synergies.json',
  BaseAvatar: 'base-Avatar-synergies.json',
  BasePoison: 'base-Poison-synergies.json',
  BaseBerserker: 'base-Berserker-synergies.json',
  BasePredator: 'base-Predator-synergies.json',
  BaseBlademaster: 'base-Blademaster-synergies.json',
  BaseRanger: 'base-Ranger-synergies.json',
  BaseCrystal: 'base-Crystal-synergies.json',
  BaseShadow: 'base-Shadow-synergies.json',
  BaseDesert: 'base-Desert-synergies.json',
  BaseSoulbound: 'base-Soulbound-synergies.json',
  BaseDruid: 'base-Druid-synergies.json',
  BaseSteel: 'base-Steel-synergies.json',
  BaseElectric: 'base-Electric-synergies.json',
  BaseSummoner: 'base-Summoner-synergies.json',
  BaseGlacial: 'base-Glacial-synergies.json',
  BaseWarden: 'base-Warden-synergies.json',
  BaseInferno: 'base-Inferno-synergies.json',
  BaseWind: 'base-Wind-synergies.json',
  BaseLight: 'base-Light-synergies.json',
  BaseWoodland: 'base-Woodland-synergies.json',
  BaseMage: 'base-Mage-synergies.json',
  BaseMountain: 'base-Mountain-synergies.json',
}

export const SYNERGIES = [
  'Alchemist',
  'Mystic',
  'Assassin',
  'Ocean',
  'Avatar',
  'Poison',
  'Berserker',
  'Predator',
  'Blademaster',
  'Ranger',
  'Crystal',
  'Shadow',
  'Desert',
  'Soulbound',
  'Druid',
  'Steel',
  'Electric',
  'Summoner',
  'Glacial',
  'Warden',
  'Inferno',
  'Wind',
  'Light',
  'Woodland',
  'Mage',
  'Mountain',
];

export const store = {
  LightAlchemist: null,
  LightMystic: null,
  LightAssassin: null,
  LightOcean: null,
  LightAvatar: null,
  LightPoison: null,
  LightBerserker: null,
  LightPredator: null,
  LightBlademaster: null,
  LightRanger: null,
  LightCrystal: null,
  LightShadow: null,
  LightDesert: null,
  LightSoulbound: null,
  LightDruid: null,
  LightSteel: null,
  LightElectric: null,
  LightSummoner: null,
  LightGlacial: null,
  LightWarden: null,
  LightInferno: null,
  LightWind: null,
  LightLight: null,
  LightWoodland: null,
  LightMage: null,
  LightMountain: null,
  ShadowAssassin: null,
  ShadowAvatar: null,
  ShadowBerserker: null,
  ShadowBlademaster: null,
  ShadowCrystal: null,
  ShadowDesert: null,
  ShadowDruid: null,
  ShadowElectric: null,
  ShadowGlacial: null,
  ShadowInferno: null,
  ShadowLight: null,
  ShadowMage: null,
  ShadowMountain: null,
  ShadowMystic: null,
  ShadowOcean: null,
  ShadowPoison: null,
  ShadowPredator: null,
  ShadowRanger: null,
  Shadowahadow: null,
  ShadowSoulbound: null,
  ShadowSteel: null,
  ShadowSummoner: null,
  ShadowWarden: null,
  ShadowWind: null,
  ShadowWoodland: null,
  ShadowAlchemist: null,
  BaseAlchemist: null,
  BaseMystic: null,
  BaseAssassin: null,
  BaseOcean: null,
  BaseAvatar: null,
  BasePoison: null,
  BaseBerserker: null,
  BasePredator: null,
  BaseBlademaster: null,
  BaseRanger: null,
  BaseCrystal: null,
  BaseShadow: null,
  BaseDesert: null,
  BaseSoulbound: null,
  BaseDruid: null,
  BaseSteel: null,
  BaseElectric: null,
  BaseSummoner: null,
  BaseGlacial: null,
  BaseWarden: null,
  BaseInferno: null,
  BaseWind: null,
  BaseLight: null,
  BaseWoodland: null,
  BaseMage: null,
  BaseMountain: null,
}

export async function loadData(base, synergy) {
  console.log(base, synergy)
  if (store[base + synergy] === null) {
    const combs = await (await fetch(BASE_URL + DATA_URLS[base + synergy])).json()
    combs.sort((a, b) => b.champions.length - a.champions.length);
    combs.sort((a, b) => {
      const bHasAvatar = b.synergies.Avatar
      const aHasAvatar = a.synergies.Avatar
      return Object.values(b.synergies).reduce((p, c) => p + c) - bHasAvatar - (Object.values(a.synergies).reduce((p, c) => p + c) - aHasAvatar)
    })
    store[base + synergy] = combs
  }

  return store[base + synergy]
}